DROP TABLE USER;
DROP TABLE COMPANY;
DROP TABLE DEPARTMENT;

CREATE TABLE USER
(
IDX INTEGER  PRIMARY KEY AUTOINCREMENT ,
ID varchar(16),
NAME varchar(100),
PASS varchar(100)
);

CREATE TABLE COMPANY(
   IDX INTEGER  PRIMARY KEY AUTOINCREMENT,
   ID varchar(8) ,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        varchar(100),
   SALARY         REAL
);

CREATE TABLE DEPARTMENT(
   ID INTEGER  PRIMARY KEY AUTOINCREMENT,
   DEPT           varchar(50) NOT NULL,
   EMP_ID         INT      NOT NULL
);
